services:
  zkevm-seqsender:
    container_name: zkevm-seqsender
    image: zkevm-seqsender
    build: .
    volumes:
      - ./test/config/test.seqsender.config.toml:/app/config.toml
      - ./test/config/test.genesis.config.json:/app/genesis.json
      - ./test/config/sequencer.keystore:/app/sequencer.keystore
      - data:/app/data
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-seqsender run --cfg /app/config.toml --network custom --custom-network-file /app/genesis.json"

volumes:
  data:
